services:
    rails-app:
        build:
            context: .
            dockerfile: Dockerfile

        command: bin/rails server -b 0.0.0.0 -p 3000

        ports:
            - "3000:3000"
        environment:
            RAILS_ENV: development
            DB_HOST: postgres
            DB_USERNAME: postgres
            DB_PASSWORD: postgres
            SECRET_KEY_BASE: ${SECRET}

        volumes:
            - .:/rails

        networks:
            - rails_bridge

        depends_on:
            - postgres
            - selenium

    selenium:
        image: selenium/standalone-chromium
        restart: unless-stopped
        networks:
            - rails_bridge


    postgres:
        image: postgres:16.1
        restart: unless-stopped
        networks:
            - rails_bridge
        volumes:
        - postgres-data:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres

    loki:
        image: grafana/loki:2.9.8
        networks:
            - rails_bridge
        ports:
            - "3100:3100"
        command: -config.file=/etc/loki/local-config.yaml

    prometheus:
        image: prom/prometheus:v2.53.4
        networks:
            - rails_bridge
        ports:
            - "9090:9090"
        volumes:
            - ./config:/etc/prometheus
            - ./prometheus/rules:/etc/prometheus/rules
        command:
            - --config.file=/etc/prometheus/prometheus.yml
            - --web.enable-remote-write-receiver

    tempo:
        image: grafana/tempo:2.6.1
        networks:
            - rails_bridge
        ports:
            - "3200:3200"
        volumes:
            - ./config:/etc/tempo
        command:
            - -config.file=/etc/tempo/tempo.yml

    alloy:
        image: grafana/alloy:v1.7.1
        networks:
            - rails_bridge
        ports:
            - "12345:12345"
            - "4317:4317"
            - "4318:4318"
        volumes:
            - ./config:/etc/alloy
            - /var/run/docker.sock:/var/run/docker.sock
        command:
            [
                "run",
                "--server.http.listen-addr=0.0.0.0:12345",
                "/etc/alloy/config.alloy",
            ]
        depends_on:
            - loki
            - prometheus
            - tempo

    grafana:
        image: grafana/grafana:13.0.1
        networks:
            - rails_bridge
        ports:
            - "3001:3000"
        environment:
            - GF_SECURITY_ADMIN_PASSWORD=admin
        volumes:
            - ./config/grafana/provisioning:/etc/grafana/provisioning
            - ./config/grafana/dashboards:/var/lib/grafana/dashboards
        depends_on:
            - loki
            - prometheus
            - tempo

    alertmanager:
        image: prom/alertmanager:latest
        networks:
            - rails_bridge
        volumes:
           - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
        ports:
            - "9093:9093"
        depends_on:
            - grafana

    jenkins:
        privileged: true
        image: jenkins/jenkins:lts
        networks:
            - rails_bridge

        ports:
            - "8080:8080"
            - "50000:50000"
        volumes:
            - jenkins_home:/var/jenkins_home
            - /var/run/docker.sock:/var/run/docker.sock
    k6:
        image: grafana/k6:latest
        container_name: k6
        volumes:
            - ./k6:/k6:ro
        working_dir: /k6
        command: run /k6/products.js
        networks:
            - rails_bridge

volumes:
  postgres-data:
  jenkins_home:

networks:
    rails_bridge:
        driver: bridge
